# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriegspiel', '0002_game_turn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turn',
            new_name='Move',
        ),
    ]
