# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kriegspiel', '0003_auto_20170113_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
